name: react打包发布
on: push

jobs:
  npm-run-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
    - name: 复制仓库内容
      uses: actions/checkout@v4

    - name: 登陆docker-hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERNAME }}
        password: ${{ secrets.DOCKERPASS }}
    
    - name: 构建并推送到docker-hub
      uses: docker/build-push-action@v5
      with: 
        push: true
        tags:  zzj1183048003/react-action-test:latest

